### ISSUE TITLE
Validate ID-number

### ISSUE THREAD

**Issue by bertfrees** [snaekobbi/pipeline-mod-mtm#18]
Björn wrote:

> - There is currently no validation on ID-number:
>   - The system does not compute when ID-number is not filled in.
>   - The system should return an error message saying that the ID-number field
>     needs to be filled in.
>   - Rules for ID-numbers are not implemented

I'll have a look at this. @snaekobbi/mtm What exactly are the rules?

**Comment by BWestling** [comment]
Hi!
I have asked Jens to answer, what our preferences are.
/Björn

**Comment by bertfrees** [comment]
Blocked on: https://github.com/daisy/pipeline-webui/issues/75

**Comment by bertfrees** [comment]
Jens said:

> If no Identifier is filled in, the job should not run, and there should be an error message saying something like “missing obligatory data: identifier”. The identifier should be in the form of PXXXXX.

So, "P" and 5 digits?

**Comment by JC-MTM** [comment]
Yes, P + five numbers.

**Comment by bertfrees** [comment]
fixed by cef960afe095f3eaab5c778d9cdb4e01654e0b2f and 3a9ac7eaba1bd229958b7cfeeff28773281b452f
