### ISSUE TITLE
Add option to insert the print page location

### ISSUE THREAD

**Issue by joeha480** [snaekobbi/pipeline-mod-mtm#22]
Add option to insert the print page location

**Comment by joeha480** [comment]
Please add details, @BWestling

**Comment by BWestling** [comment]
Hi, 
We would like to have the following solution for the print page location (a little nicer than the full line across the page):
- Full cell in left margin on the line where the print page location is situated.
- Two cells with dot 3 and 4 to mark the position (surrounded by space).
- Text continues after the mark on the same line.

See also example (jpg-file).

/Björn
![solution on print page location](https://cloud.githubusercontent.com/assets/8458520/14985447/c9e4460c-1147-11e6-9872-11345f744802.jpg)

**Comment by bertfrees** [comment]
OK, thanks for the info. That should be doable.

**Comment by BWestling** [comment]
Great, thanks!
