### ISSUE TITLE
Datatypes in Web GUI

### ISSUE THREAD

**Issue by joeha480** [snaekobbi/pipeline-mod-mtm#4]
It would be useful to have additional datatypes, for example integers or a regex in the web GUI in order to restrict user input.

**Comment by josteinaj** [comment]
Very much related (but not quite duplicate): daisy/pipeline-webui#34

**Comment by josteinaj** [comment]
see: snaekobbi/issues#19 and snaekobbi/issues#20

**Comment by bertfrees** [comment]
Datatypes can now be declared in the script like this: https://github.com/daisy/pipeline-mod-braille/issues/85.
