### ISSUE TITLE
Identifier cannot be passed to pef

### ISSUE THREAD

**Issue by joeha480** [snaekobbi/pipeline-mod-mtm#5]
Currently, the identifier cannot be set for the generated pef-file. This is supported in Dotify, but the logic is a bit convoluted and should perhaps be improved first.

**Comment by bertfrees** [comment]
OK. Shall I assign to you or can I help with something?

**Comment by joeha480** [comment]
Related issue:
https://github.com/joeha480/dotify/issues/72
